### ISSUE TITLE
Explain the Take Away of the Lab

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/activerecord-crud#1]
The spec file here is pretty magical and important. The point of the lab is to recognize all the sort of methods that AR provides on a convention-oriented class (that wraps a DB table). You get accessors for each column. CRUD methods. Finders. Etc. This lab should either tell the student or force the student somehow to recognize the common AR interface.

**Comment by AnnJohn** [comment]
Iceboxing the issue.

**Comment by jmburges** [comment]
Agreed! This is really important that they understand but simply subclassing and attaching to a database you get a lot of magic. At the beginning-ish metion that while the model has no methods in it, it's superclass has so much, and uses metaprogramming to figure out the rest. Then point them to the AR docs for all of the methods available to them

**Comment by aviflombaum** [comment]
Ya, i think this is going to come in helpful in the Rails unit pretty soon so we should expect to thaw this and re-write or re-use this lab.

**Comment by danny-sullivan** [comment]
Updated.
