### ISSUE TITLE
Incorrect Method name causes Rspec Error

### ISSUE THREAD

**Issue by the-widget** [learn-co-curriculum/activerecord-crud#22]
The snippet below is from `movies_controller.rb`. It fails the test, but only because the given method name is incorrect. Upon changing the word "different", to "multiple". The tests pass. If that was to intentionally challenge us, then right on! It made me pay attention to detail and examine the error message closely.
```
def can_find_by_different_attributes
  # title == "Title"
  # release_date == 2000, 
  # director == "Me"
  Movie.find_by(title: "Title", release_date: 2000, director: "Me")
end
```

**Comment by AnnJohn** [comment]
fixed this. thank you!
