### ISSUE TITLE
Typo between method / spec file, and one method doesn't seem to test

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/activerecord-crud#25]
1. method is named different than spec file: 
FAILS: 
def can_find_by_**different**_attributes
  # title == "Title"
  # release_date == 2000, 
  # director == "Me"
  Movie.find_by(title: "Title")
end

PASSES: 
def can_find_by_**multiple**_attributes
  # title == "Title"
  # release_date == 2000, 
  # director == "Me"
  Movie.find_by(title: "Title")
end

2. a)This one doesn’t seem to factor into the tests. Code does not affect pass/fail count.
   b)Typo:  Updtate
**def can_be_found_updated_and_saved**
  # Updtate the title "Awesome Flick" to "Even Awesomer Flick"
  Movie.create(title: "Awesome Flick")
  Movie.find(title: "Awesome Flick")
  Movie.update(title: "Even Awesomer Flick")
  Movie.save
end

**Comment by lukegrecki** [comment]
Yes neither `can_be_found_updated_and_saved` nor `can_update_using_update_method` is tested. It seems the solutions are written into the specs themselves.
