### ISSUE TITLE
Edge case in the spec

### ISSUE THREAD

**Issue by achasveachas** [learn-co-curriculum/activerecord-crud#31]
When I was doing the spec for 'can_get_size_of_the_database' I was thinking of how to approach it, My first try was to do Movie.last.id which would give the ID of the last movie added which would be the size of the database **under normal circumstances**. 
I then realized that that shouldn't be the correct answer because it won't account for a case where a record was deleted, nevertheless it still passed the test. 
You might want to change the test to account for that? Maybe by creating a movie with an ID greater than 5?

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by sgharms** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
