### ISSUE TITLE
The Wachowski Brothers are now the Wachowski Sisters

### ISSUE THREAD

**Issue by tsengsational** [learn-co-curriculum/activerecord-crud#36]
noticed that in the spec, Movie.new tests for the Matrix movie and lists movie.director = "The Wachowski Brothers"

Both Wachowskis have transitioned to female and are now the Wachowskis or the Wachowski Sisters.

**Comment by gj** [comment]
Fixed here: https://github.com/learn-co-curriculum/activerecord-crud/commit/2fa3410f150104db681f30faead4b8fe38f3e63a

Thanks @tsengsational !
