### ISSUE TITLE
No Read Me or spec folder with tests

### ISSUE THREAD

**Issue by ThePeej** [learn-co-curriculum/activerecord-crud#39]
There are currently no specs/tests to run. There is also no ReadMe as it looks like the readme was removed a few days ago and not replaced. As of now, when the lab page on Learn.co loads, it is completely empty, and there are no tests to pass or even work towards.

**Comment by sgharms** [comment]
We've seen the issue, we have a theory of what went wrong, we have written
a fix. We will confirm what happened with the individual that made the
changes, and if we agree on the remedy we will deploy it today.

Steven

**Comment by sgharms** [comment]
Fixed by #40
