### ISSUE TITLE
Clarify the can_be_created_in_a_block method

### ISSUE THREAD

**Issue by unenlightened** [learn-co-curriculum/activerecord-crud#49]
README instructions say that "In each method the __ corresponds to a line of code you will need to write to make the spec pass."

Add the __ to show that more code should be added.

Line 25  of movies_controller.rb can be updated from ---def can_be_created_in_a_block(args = {})--- to ---def can_be_created_in_a_block(args = { __ })---

That's the area that needs to be updated to pass the 'can be created in a block when no args are passed' on line 72 of movie_spec.rb

**Comment by curiositypaths** [comment]
Hi there,

Thank you for bringing this to our attention. We updated the `can_be_created_in_a_block` method definition.

As always thank you for contributing!
