### ISSUE TITLE
ambiguous movie_controller.rb method name change

### ISSUE THREAD

**Issue by developerjigr** [learn-co-curriculum/activerecord-crud#52]
Method names in movie_controller.rb file (below) and the spec file are ambiguous. 
They ask to return the first item in the database where as it is expecting the title of the first item in the database.

```
def can_get_the_first_item_in_the_database
end

def can_get_the_last_item_in_the_database
end
```

Method names

**Comment by Joshua-Miles** [comment]
Should be fixed as of 26069389301cfd46c0dd35490baa363fcec53175
