### ISSUE TITLE
Problem running rspec test

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/activerecord-crud#53]
One student got this error when trying to run bundle install (needed to run rspec test):

An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that &#96;gem install json -v '1.8.3' --source 'https://rubygems.org/'&#96; succeeds before bundling.

In Gemfile:
  sinatra-activerecord was resolved to 2.0.9, which depends on
    activerecord was resolved to 4.2.6, which depends on
      activemodel was resolved to 4.2.6, which depends on
        activesupport was resolved to 4.2.6, which depends on
          json

Running 'gem install json -v '1.8.3' did not work and threw error messages. Solution below:

$ bundle update json
$ bundle install

After this rspec could run.

**Comment by drakeltheryuujin** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the Learn.co curriculum. This sounds like an environment issue, which we unfortunately do not have the capacity to support at this time. I would recommend googling around about the problem.

You can also try popping into [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ), where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can provide additional help. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

I'm sorry, and good luck! 💙
