### ISSUE TITLE
Tests implicitly check for in_theatres but explicitly for in_theaters

### ISSUE THREAD

**Issue by critsmet** [learn-co-curriculum/activerecord-crud#59]
Students can create table schema correctly for models but tests still fail. Tests check for in_theatRES but the rest of the lab uses in_theatERS.

**Comment by maxwellbenton** [comment]
Hi @critsmet,

I've taken a look and updated this lesson, but I'm having difficulty reproducing this issue and did not see any use of in_theat**res** present in the tests. 

I'm going to close this for now, but if you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
