### ISSUE TITLE
Lab is not marked as passed in the Full stack tree 

### ISSUE THREAD

**Issue by lauratravin** [learn-co-curriculum/activerecord-crud#60]
The lab is not marked as done in the full stack tree on the left side (curriculum) despite it was solved.
[Boodstrap issue.pdf](https://github.com/learn-co-curriculum/activerecord-crud/files/2617749/Boodstrap.issue.pdf)

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to the Learn platform.

Please send your details to: support@learn.co.

[Raising issues on GitHub][raise] should be reserved for problems with
the curriculum itself (doesn't work, throws a Ruby error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
